#!/bin/bash

if [ "${TYPE}" == "TCP" ] || [ "${TYPE}" == "tcp" ]; then
  if [[ -z "${PORT}" ]]; then
    PORT=80
  fi
  echo
  echo tcping ${HOSTNAME:=localhost} on ${PORT}
  echo
  ./tcping -c 1 -4 ${HOSTNAME} ${PORT}
else
  echo
  echo ping ${HOSTNAME:=localhost}
  echo
  ./ping -c 1 ${HOSTNAME}; sleep ${TIMEOUT}
fi