#!/bin/bash

if [ "${TYPE}" == "TCP" ] || [ "${TYPE}" == "tcp" ]; then
  if [[ -z "${PORT}" ]]; then
    PORT=80
  fi
  echo
  echo tcping ${HOSTNAME:=localhost} on ${PORT}
  echo
  while true; do ./tcping -c 1 ${HOSTNAME} ${PORT}; sleep ${TIMEOUT:=300}; done
else
  echo
  echo ping ${HOSTNAME:=localhost}
  echo
  while true; do ping -c 1 ${HOSTNAME}; sleep ${TIMEOUT:=300}; done
fi