name: Docker container build

on:
  workflow_run:
    workflows: ["CodeQL"]
    types:
      - completed
    branches: ["main"]
    tags: ["v*.*.*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Extract Version
        id: version_step
        run: |
          echo "version=${GITHUB_REF#"refs/tags/v"}" >> $GITHUB_ENV
          echo "version_tag=${GITHUB_REPOSITORY}:${GITHUB_REF#"refs/tags/v"}" >> $GITHUB_ENV
          echo "latest_tag=${GITHUB_REPOSITORY}:latest" >> $GITHUB_ENV
      - name: Print Version
        run: |
          echo ${{ env.version }}
          echo ${{ env.version_tag }}
          echo ${{ env.latest_tag }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: "v2.1.1"

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.5.0

      - name: Setting Go version
        uses: actions/setup-go@v5.0.2
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build Docker image using Makefile
        run: make gitHubActions

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            pouriyajamshidi/tcping
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}